= Neo4j WorkSpace Guide

== Parameters
=== About parameters

Cypher supports querying with parameters. 
A parameterized query is a query where placeholders are used for parameters and the parameter values are supplied at execution time. 
This means developers don't have to resort to string building to create a query. 
Also, parameters make caching of execution plans much easier for Cypher, thus leading to faster query execution times. 
You can read more about parameters https://neo4j.com/docs/cypher-manual/current/syntax/parameters/[here].

=== Setting and Managing Parameters

Parameters can be created and managed either via the parameters sidebar or by invoking the `:param` command in a Cypher editor.

The Parameters sidebar provides dedicated UI inputs for most of the neo4j https://neo4j.com/docs/cypher-manual/current/values-and-types/property-structural-constructed/#property-types[property types].
There are a few exceptions such as the https://neo4j.com/docs/cypher-manual/current/values-and-types/spatial/#spatial-values-point-type[Point] type and the setting of https://neo4j.com/docs/cypher-manual/current/values-and-types/property-structural-constructed/#constructed-types[constructed types].
To support the setting of these types via the UI, we also provide a special option of `evaluated` in the type dropdown.
This allows you to express any parameter type as you would using the right-hand part of the command syntax inlinecode:++:param pointParam => Point({x:1, y:1})++[], in this example `Point({x:1, y:1})` as the value to be evaluated.

For types that are not supported by the UI, or indeed if you prefer working with commands, the `:param` command provides the ability to set and manage parameters.
The following arguments are supported:

* inlinecode:++:param list++[] or inlinecode:++:param++[] - Lists all parameters
* inlinecode:++:param clear++[] - Clears all parameters
* inlinecode:++:param {a: 1}++[] - Sets the parameter `a` to the value `1`
* inlinecode:++:param {a: 1, b: 2}++[] - Sets the parameter `a` to the value `1`, `b` to the value `2`

The arrow syntax inlinecode:++:param a => 1++[] is also supported to set parameters individually.

=== Parameter evaluation

When you declare a parameter, it is evaluated by an implicit Cypher `RETURN`, that’s to say, any value you set a parameter to, is first evaluated as a simple `RETURN <value>`. 
For example, in:

[source,cypher]
----
:param {
  param1: 1,
  param2: "Brown Fox",
  param3: date("2020-01-01")
}
----

each parameter value for `param1` through to `param3` is evaluated in a Cypher `RETURN` ensuring they obtain the correct neo4j data type.  
This means that inlinecode:++RETURN date("2020-01-01")++[] evaluates the Neo4j Date https://neo4j.com/docs/cypher-manual/current/syntax/values/[type].

=== Referencing a parameter

Parameters are identified in Cypher statements by a `$` sign. 
The parameter `param3` declared above could be used like this:

[source,cypher]
----
MATCH (m:Movie {
 releaseDate: $param3
})
RETURN m
----

to return all Movies with the release date `2020-01-01` set in `param3`.


=== A note on the system database

If you are using a multi-database DBMS, parameters can't be declared when using the `system` database. 
Switch to a different database and declare, then switch back to the `system` database and use the parameters.


